### ISSUE TITLE
Getting file not found error when working with susi_server in the installation script

### ISSUE THREAD

**Issue by pranav1698** [fossasia/susi_installer#107]
#### Describe the bug
During the execution of install script in the master branch,
I get an unexpected error:
`cp: cannot stat 'susi_server/systemd/ss-susi-server.service.in': No such file or directory
`
This can be because of different file-structure in the susi-server installed locally.

#### Expected behavior
Installation of susi_installer in the desktop without any errrors

#### Desktop (please complete the following information):
 - OS: Ubuntu 18.10

**Comment by norbusan** [comment]
Closing bug since PR is merged
