### ISSUE TITLE
Improper install instructions

### ISSUE THREAD

**Issue by ajax711** [fossasia/susi_installer#11]
#### Describe the bug
[Ubuntu.md](https://github.com/fossasia/susi_installer/blob/development/docs/ubuntu_install.md 
) has 

```
$ git clone https://github.com/fossasia/susi_linux.git
$ cd susi_linux
$ ./install.sh

```

but susi_linux repo doesn't have an install script.

**Comment by norbusan** [comment]
Working on that https://github.com/norbusan/susi_installer/tree/desktop-docs
