### ISSUE TITLE
Not Loading, White blank screen (Windows 10, 

### ISSUE THREAD

**Issue by minkyman-coding101** [fossasia/susi_installer#113]
![image](https://user-images.githubusercontent.com/56607897/81280670-bbc11c80-9050-11ea-9004-92d224504a92.png)

**Computer specs above**

Install NPM / Node latest version, Used NPM install (Admin) then NPM Run, every time turns out like this - 
![image](https://user-images.githubusercontent.com/56607897/81280952-23776780-9051-11ea-91fb-43f3589baa1d.png)

**Comment by norbusan** [comment]
This is not an issue of SUSI.AI installer, but of [SUSI Desktop](https://github.com/fossasia/susi_desktop), please report there.
