### ISSUE TITLE
The installation script mistakenly call pip instead of pip3

### ISSUE THREAD

**Issue by hongquan** [fossasia/susi_installer#115]
#### Describe the bug

Recently, at a SUSI workshop, some users failed to install SUSI, getting "pip not available" error

#### To Reproduce
1. Run

```
curl --proto '=https' --tlsv1.2 -sSf 
https://raw.githubusercontent.com/fossasia/susi_installer/development/install.sh | bash
```

After a while, it breaks at:

```
Error on line 72: bash $tmpdir/install-requirements.sh --system-install --with-deepspeech
```

and "pip not available" before that.

#### Expected behavior

It should run until finish

#### Desktop (please complete the following information):
 - OS: Ubuntu 20.04

#### Additional context

I saw the error from user screen, via Jitsi, so I didn't have full error log.

**Comment by norbusan** [comment]
Indeed, there was a stray copy of `pip` that is used to check the version of deepspeech installed, fixed now. Thanks!
