### ISSUE TITLE
susi_installer support for arch linux 

### ISSUE THREAD

**Issue by sonuishaq67** [fossasia/susi_installer#117]
#### Is your feature request related to a problem? Please describe.
Yes It currently doesnt support arch linux but i can work on that 

#### Describe the solution you'd like
bash install-requirements.sh --system-install --with-deepspeech doesnt work for arch linux because its not defined

#### Describe alternatives you've considered
I can add the script for installing on arch linux 

#### Additional context
If you can please do assign it to me so i can start working on it

**Comment by norbusan** [comment]
Hi @sonuishaq67 
sounds like a good idea, but please don't add a new script, but extend the current script. It has already settings and adaptions for three different installation modes, we need to add another one for Arch linux.

**Comment by norbusan** [comment]
Ah, there is nothing to assign, go ahead and start working on it, and send a PR.

**Comment by sonuishaq67** [comment]
Yup that's what I meant
Extending the script .
I'll start working on it then

**Comment by sonuishaq67** [comment]
Hey @norbusan I sent a pr regarding this #118

**Comment by norbusan** [comment]
I'll look into it asap, thanks
