### ISSUE TITLE
Re-configuration of WLAN

### ISSUE THREAD

**Issue by norbusan** [fossasia/susi_installer#12]
After setting up the wlan ssid, and then moving to a different wlan, connection is completely broken and there is no way to go back to ssid configuration.

We need to skill that toggles the access point mode, and the skill needs to be available locally.

**Comment by stealthanthrax** [comment]
@norbusan , we use the `rwap.sh` script

**Comment by norbusan** [comment]
Yes I know, but the problem is that you cannot **start** it.

I have connected my speaker to wlan ssid `aaaa`. Then I move to a different place and the speaker needs to connect to ssid `bbbb`. But this cannot be done, because it is already in client mode.

I can also not log into the device and switch the wlan mode.

Thus, we need some other way to trigger this.

**Comment by norbusan** [comment]
I consider this closed via PR https://github.com/fossasia/susi_installer/pull/13 that was merged already, thus closing this issue
