### ISSUE TITLE
Installers fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by alok760** [fossasia/susi_installer#2]
#### Describe the bug
The installer tries installing the vlc-bin package which is not available for ubuntu-16.04

#### To Reproduce
install on ubuntu 16.04

#### Desktop (please complete the following information):
 - OS: ubuntu
 - Version 16.04

#### Additional context
After a fresh install of Ubuntu, the following things also needs to be done.
- dpkg-dev must be installed before running the install script.
- Universe repository must be enabled.

**Comment by norbusan** [comment]
How did you install on Ubuntu 16.04? It should bail out:
```
    Ubuntu)
        case "$version" in
            18.*|19.*|20.*) isBuster=1 ;;
            16.*|17.*) ;;
            *) echo "Unsupported Ubuntu version: $version" >&2 ; exit 1 ;;
        esac
        ;;
```

Can you please send:
- output of `lsb_release -i -s`
- output of `lsb_release -r -s`
and maybe what other packages are needed.

**Comment by norbusan** [comment]
Ok, I will look into it. Can you please send the output of `lsb_release -i` and `lsb_release -r`.

How does one "enable universe repository" (never used Ubuntu, sorry)

Thanks

**Comment by norbusan** [comment]
Can you try the `ubuntu16` branch? I added checks for ubuntu, switch to vlc-nox, and enable universe. Thanks for your feedback

**Comment by alok760** [comment]
> Ok, I will look into it. Can you please send the output of lsb_release -i and lsb_release -r

![image](https://user-images.githubusercontent.com/14289201/57588936-df36b180-7539-11e9-8da3-312d29a61b6d.png)

**Comment by alok760** [comment]
> Can you try the ubuntu16 branch? I added checks for ubuntu, switch to vlc-nox, and enable universe. Thanks for your feedback

I'll run the installer and update here

**Comment by alok760** [comment]
> I'll run the installer and update here

![image](https://user-images.githubusercontent.com/14289201/57589008-2ffada00-753b-11e9-925e-784d28002dfd.png)

**Comment by norbusan** [comment]
Ok, more stuff is missing. I will install myself 16.04 in a virtual machine and test.

Please wait a bit.

**Comment by alok760** [comment]
> Ok, more stuff is missing. I will install myself 16.04 in a virtual machine and test.
> 
> Please wait a bit.

@norbusan No need, I already have a lot of VMs set up for testing :) and I want to work on this issue.

**Comment by norbusan** [comment]
I pushed a new change - shell syntax error - please retry. At least universe should be enabled then

**Comment by alok760** [comment]
vlc-plugin-base and vlc-plugin-video-splitter are packaged for Ubuntu >=18.04 (https://packages.ubuntu.com/search?keywords=vlc-plugin-base)

For ubuntu16.04 we have these - https://packages.ubuntu.com/search?suite=xenial&searchon=names&keywords=vlc

**Comment by norbusan** [comment]
Updated the installer to only install vlc-nox on ubuntu16.04.

**Comment by norbusan** [comment]
Ok, I consider disabling support for 16.04, there are too many problems here:
- swig is too old, we cannot compile snowboy for it
- snowboy somehow cannot be installed from pip fossasia, nto sure why
- python_audio seems to be too old, needs recompilation, which fails

Probably many more things.

Are you sure we need 16.04 support? Can we start with 18.04LTS?

**Comment by alok760** [comment]
yes, 16.04 seems problematic for many things.
you can close this issue

**Comment by norbusan** [comment]
I close it for now, but have asked on gitter, too. Maybe we can reconsider later on.

Have you tried 18.04?
