### ISSUE TITLE
Add support for more USB media discovery skills 

### ISSUE THREAD

**Issue by alok760** [fossasia/susi_installer#28]
#### Is your feature request related to a problem? Please describe.
- Add support for more USB media discovery skills such as 
    - SUSI, play rock music from USB (a specific genre)
    - SUSI, play all maroon5 songs from USB (a specific artist)
- This Issue requires fetching metadata of all audio files in the USB and create skills on the fly

**Comment by norbusan** [comment]
We need to standardize on what utterances we want to support. Here is a proposal for supported features
```
<AUDIOSKILLS> ::= <PLAY> | <NEXT> | <PREV> | <PAUSE> | <RESUME> | <STOP> | <SHUFFLE>

<PLAY>  ::= play <WHAT> [from <WHERE>]
        plays a song or group of songs
        if no [from <WHERE>] is given, use LOCAL if available, otherwise youtube

<WHERE> ::= <LOCAL> | <STREAMING>
        defines the source of the music

<LOCAL> ::= usb | stick | local | ...
        anything that can be considered local

<STREAMING> ::= youtube | tidal | ...
        all kind of internet services

<WHAT>  ::= <STRING> | folder | genre <STRING> | artist <STRING> | mood <STRING> |  ...
        what describes the song(s) to be played
        folder: play the first top level folder containing music
        genre: select genre according to <STRING>
        artist: select artist according to <STRING>
        mood: select mood according to <STRING>
        If none of the key words is given, <STRING> is used to search a match.
        Match searching order: artist, genre, song, folder (??)

<STRING> ::= <any utterance>

<NEXT>  ::> next [ artist | genre | folder | ?? ]
        skip to the next song in the playlist, or
        next artist/genre/folder available

<PREV>  ::> prev [ artist | genre | folder | ?? ]
        skip to the next song in the playlist, or
        next artist/genre/folder available

<SHUFFLE> ::= 
        not clear, possible options
        - shuffle current play list
        - shuffle works like play but shuffles songs and play plays in order?
```
This needs changes in the server, in the python access part, as well of course support for querying meta data of auto songs in the susi client

I see two options:
- pre-processing on load time:
  when the usb stick is plugged in, all songs are analyzed and skills for all possible combinations are generated
- on the fly processing
  the meta data is saved say in a sqlite db and queried from susi_linux and actual songs selected during skill processing (busy state) time.

**Comment by alok760** [comment]
>pre-processing on load time:
>when the usb stick is plugged in, all songs are analyzed and skills for all possible combinations are generated

@norbusan I worked on this here for artists- https://github.com/alok760/susi_installer/tree/artist
It works fine.
I'll just make a draft PR here 
let me know your views

**Comment by norbusan** [comment]
@alok760 Yes, this is the first approach I mentioned. This is for sure the sort-term easiest way, but might be a bit a pain with large amounts of audio data etc.

**Comment by alok760** [comment]
>on the fly processing
>the meta data is saved say in a sqlite db and queried from susi_linux and actual songs selected during skill processing (busy state) time.

I also like this idea and even proposed something similar on gitter but with media discovery on the busy state. Like you said having media discovery(creating metadata db) on USB event is a better idea. This way song playback won't depend on the offline server only.
