### ISSUE TITLE
volume endpoint in the soundserver doesn't work on raspberry pi

### ISSUE THREAD

**Issue by alok760** [fossasia/susi_installer#38]
#### Describe the bug
- On trying to change the volume, the server sends an 'OK' response but the volume doesn't change on raspberry pi. It works fine on other desktop platforms.

![image](https://user-images.githubusercontent.com/14289201/59960063-afd37700-94df-11e9-97c5-601e018e717f.png)

https://github.com/fossasia/susi_installer/blob/74518528027f53c379cd4bb9b93307d229ba33a1/raspi/soundserver/soundserver.py#L39

#### To Reproduce
- use the endpoint/ control webpage to control the volume of the smart speaker

**Comment by norbusan** [comment]
Interesting. Please investigate!
