### ISSUE TITLE
Extra Links Committed in the repo

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_installer#40]
#### Describe the bug
The links to sound server are being made by the installation script and hence imo, should not be present in the repo.
https://github.com/fossasia/susi_installer/blob/development/raspi/soundserver/vlcplayer

#### Additional context
To remove these

**Comment by norbusan** [comment]
Hmm, good point. We should remove them and add them to gitignore, and then locally they can be added again for local testing (this is why they were there in the first place)
