### ISSUE TITLE
susi_installer fails on compiling snowboy

### ISSUE THREAD

**Issue by mdl2000** [fossasia/susi_installer#48]
Hello Everyone!

I tried to using susi_installer, but it fails while compiling snowboy

Screenshots:

It was showing the following error :-

![image](https://user-images.githubusercontent.com/46283486/60383144-e9c9ed80-9a8a-11e9-85fb-9c566dbc04d3.png)

 Desktop:
 - OS: Linux Mint 19.1
 - Browser:Firefox
 - Version:67.0.4 (64-bit)

**Comment by norbusan** [comment]
Interesting. It should not be necessary to compile snowboy, as we prepared pre-compiled packages already.

Could you tell me the output of
```
python3 --version
```

Thanks

**Comment by mdl2000** [comment]
@norbusan It's Python 3.6.8

**Comment by norbusan** [comment]
Hmmm, that is strange. There is a binary package available for this version.
Which version of pip is installed, please check with pip --version

I will start a virtual machine with mint 9.1 and see whether I can reproduce that.

Ah, could you capture the full output of the install run and attach it here?

**Comment by norbusan** [comment]
@mdl2000 Got your problem solved?
