### ISSUE TITLE
Installer not working on Ubuntu 18.04 and 19.04

### ISSUE THREAD

**Issue by alok760** [fossasia/susi_installer#5]
#### Describe the bug
- The installer quits after installing python dependencies.

#### To Reproduce
1. Use installer on ubuntu 18.04/19.04

#### Screenshots

![image](https://user-images.githubusercontent.com/14289201/57652151-912eb600-75ec-11e9-86d9-488c110a183c.png)

#### Desktop (please complete the following information):
 - OS: Ubuntu
 - Version : 18.04/19.04

**Comment by norbusan** [comment]
That is interesting... I need to run it under set -x to see what has happened. Maybe the recent change of set -o pilefail?

**Comment by norbusan** [comment]
@alok760 ok I know why: the default python3 there is 3.6 (!) and we don't have 3.6 versions of the packages on rubygem, only 3.5 and 3.7 ... *what*a*pain* this python is.

**Comment by norbusan** [comment]
@alok760 I have updated the python modules on the ruby gem server for python3.6 which is the default on 18.04. Furthermore, I have fixed a stupid error with the `set -e` which triggered the exit (calling `ret=$(pip3 show $pkg)` for a missing package under `set -e` immediately terminated the script ;-)

I just installed it into a clean Ubuntu 18.04 system and could start server and client afterwards, recognition (even in the qemu run!!) did work, so I am closing this issue.

If you find other problems, please let me know again. Thanks!
