### ISSUE TITLE
susi server fails to start on device

### ISSUE THREAD

**Issue by alok760** [fossasia/susi_installer#54]
#### Describe the bug
Susi server fails to start in the new image - https://github.com/fossasia/susi_installer/releases/tag/test-20190630.0

![image](https://user-images.githubusercontent.com/14289201/60429914-b6699900-9c19-11e9-9e46-abb8d16a4851.png)

**Comment by norbusan** [comment]
Hmm, the installer creates a link 
```
susi_server/data -> /home/pi/SUSI.AI/susi_server_data
```
and that directory is created, at least in my image ...

Do you have that?

**Comment by hongquan** [comment]
@norbusan In _ss-susi-server.service_, you also should specify "working directory" to avoid those directory resolution problem.

**Comment by norbusan** [comment]
@hongquan @alok760 Ahh, the final `tail` error is irrelevant, the problem is that `susi_server` is broken, as shown in the line
```
Error: Unable to initialize main class ai.susi.SusiServer
Caused by: java.lang.NoClassDefFoundError: org/eclipse/jetty/server/Handler
```
Nothing I can do, I will report it to susi_server
