### ISSUE TITLE
Cache Raspbian images on TRAVIS CI

### ISSUE THREAD

**Issue by alok760** [fossasia/susi_installer#6]
#### Is your feature request related to a problem? Please describe.
- Every time Travis CI is triggered a raspbian image is downloaded and unzipped.
https://github.com/fossasia/susi_installer/blob/857cab593113068dacb16957a6ee97463b62d5e0/.travis/create-image#L25-L26

#### Describe the solution you'd like
Frequent downloading can be avoided using - https://docs.travis-ci.com/user/caching/

I will like to work on this

**Comment by alok760** [comment]
upon further research - https://docs.travis-ci.com/user/caching/#things-not-to-cache

**Comment by hongquan** [comment]
So, the issue is that Travis caches things on cloud storage, not the same LAN or same machine, so it will not have better download speed.

**Comment by norbusan** [comment]
Seems so. 
I am currently testing (in extra branch) travis tests for debian stretch and buster, ubuntu 18.04 and 19.04, all via .travis.yml building. Needs a bit more, I am running the tests locally now.
