### ISSUE TITLE
sudo echo foo > file won't work

### ISSUE THREAD

**Issue by orangecms** [fossasia/susi_installer#73]
#### Describe the bug
See https://github.com/fossasia/susi_installer/blob/development/docs/ubuntu_install.md#additional-steps-required-for-ubuntu-1804
`sudo echo foo > file` won't work. Instead of redirecting to a file, pipe through `tee`. And instead of overwriting it blindly, appending would be the way to go. Users should audit the file themselves also instead of echoing something they would probably not understand to avoid compromising their system.

#### To Reproduce
1. `sudo touch /tmp/foo`
2. `sudo echo bar > /tmp/foo`

#### Expected behavior
Offer a package instead or provide an understanding of what the commands do.

#### Desktop (please complete the following information):
 - OS: [e.g. Windows 10, Ubuntu 18.10]
 - Browser [e.g. Chrome, Safari]

#### Smartphone (please complete the following information):
 - Browser [e.g. stock browser, Safari]

**Comment by norbusan** [comment]
I don't see this anymore in the latest version, closing this issue
