### ISSUE TITLE
Add option to add more WiFi Network credentials

### ISSUE THREAD

**Issue by alok760** [fossasia/susi_installer#85]
#### Is your feature request related to a problem? Please describe.
- If the user wants to move the device or have multiple access points, each time the network changes the user has to reset the device to access point mode.
#### Describe the solution you'd like
- Allow configuring more than one WiFi network in order to make the smart speaker connect to more than one wifi network depending on the availability

**Comment by norbusan** [comment]
Great idea! I am fully in support of that.
