### ISSUE TITLE
Add a local anonymous user at the time of installation

### ISSUE THREAD

**Issue by alok760** [fossasia/susi_installer#95]
### Problem
- The webclient currently connects to the local server running on the device.
- Features which are available only after login such as dashboard, my skills, bots and my devices are not available on the local client
![image](https://user-images.githubusercontent.com/14289201/63223845-31dad600-c1d9-11e9-8470-f80f17b8c57f.png)

### TO-DO
- Add a local anonymous user at the time of installation.
- Make the local webclient auto-login to the created account.

**Comment by norbusan** [comment]
Any progress?
